// Quiz Action Types
export const QUIZ_ACTIONS = {
  START_QUIZ: 'START_QUIZ',
  SET_ANSWER: 'SET_ANSWER',
  NEXT_QUESTION: 'NEXT_QUESTION',
  PREV_QUESTION: 'PREV_QUESTION',
  GO_TO_QUESTION: 'GO_TO_QUESTION',
  TOGGLE_MARK_REVIEW: 'TOGGLE_MARK_REVIEW',
  UPDATE_TIME: 'UPDATE_TIME',
  SUBMIT_QUIZ: 'SUBMIT_QUIZ',
  RESET_QUIZ: 'RESET_QUIZ',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  AUTO_SAVE: 'AUTO_SAVE',
};
